docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Introduction: intro.md
    - 'Authentication adapter': auth-adapter.md
    - 'User repository': user-repository.md
site_name: Authentication middleware
site_description: 'Authentication middleware for Expressive and PSR-7 applications'
repo_url: 'https://github.com/zendframework/zend-expressive-authentication'
copyright: 'Copyright (c) 2017 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
